@baseUrl = http://127.0.0.1:10080/api

###[Store-API]###

GET {{baseUrl}}/store/1 HTTP/1.1

###

GET {{baseUrl}}/stores HTTP/1.1

###[Food-API]###

GET {{baseUrl}}/food/1 HTTP/1.1

###

GET {{baseUrl}}/food/4 HTTP/1.1

###

GET {{baseUrl}}/food HTTP/1.1

###

POST {{baseUrl}}/food HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "あんぱん",
    "originalPrice": 600,
    "salePrice": 300,
    "startTime": "1300",
    "endTime": "1545",
    "amount": 3,
    "allergys": [
    {
        "id": 1,
        "name": "卵"
    },
    {
        "id": 3,
        "name": "乳"
    },
    {
        "id": 4,
        "name": "小麦"
    }
    ],
    "image": "https://dl.dropboxusercontent.com/s/fxss9wae0iq143q/an-pan.jpg",
    "storeId": 2,
    "storeName": "滝川パン"
}

###

POST {{baseUrl}}/food HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "あんぱん",
    "originalPrice": 600,
    "salePrice": 300,
    "startTime": "1300",
    "endTime": "1545",
    "amount": 3,
    "allergys": [],
    "image": "https://dl.dropboxusercontent.com/s/fxss9wae0iq143q/an-pan.jpg",
    "storeId": 2,
    "storeName": "滝川パン"
}

###[Trade-API]###

POST {{baseUrl}}/trade HTTP/1.1
Content-Type: application/json

{
    "id": 111,
    "userId": 2,
    "storeId": 1,
    "foodId": 1,
    "amount": 4,
    "receiveTime": "2030"
}

###

GET {{baseUrl}}/trade/1 HTTP/1.1

###

PATCH  {{baseUrl}}/trade/complete/2 HTTP/1.1
Content-Type: application/json

{
  "userId": 1,
  "tradeId": 4
}

###

GET {{baseUrl}}/trade/store/1 HTTP/1.1


###[Favorite-API]###

GET {{baseUrl}}/favorite/1 HTTP/1.1

###

POST {{baseUrl}}/favorite HTTP/1.1
Content-Type: application/json

{
    "userId": 2,
    "storeId": 2,
    "storeName": "滝川パン"
}

###

DELETE {{baseUrl}}/favorite/11 HTTP/1.1

###[User-API]###

POST {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "山下",
    "lastName": "昂太",
    "firstNameKana": "ヤマシタ",
    "lastNameKana": "コウタ",
    "mail": "test@etaste-jp.com",
    "password": "testtest"
}

###

POST {{baseUrl}}/user/login HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "mail": "k_yamashita@etaste-jp.com",
    "password": "aa"
}

###

# @name login
POST {{baseUrl}}/user/login HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "mail": "k_yamashita@etaste-jp.com",
    "password": "aaa"
}

@authToken = {{login.response.body.$.token}}

###

GET {{baseUrl}}/home HTTP/1.1
Authorization:Bearer {{authToken}}

###

GET {{baseUrl}}/user/logout HTTP/1,1
Authorization:Bearer {{authToken}}
Content-Type: application/json

{
    "id": 1
}